---
swagger: "2.0"
info:
  description: "APIs to cater for Master Data Configuration for Front Office Operations\
    \ in OPERA Cloud.<br /><br /><p>This document and all content within is available\
    \ under the Universal Permissive License v 1.0 (http://oss.oracle.com/licenses/upl).\
    \ Copyright c 2021 Oracle and/or its affiliates.</p>"
  version: "21.1"
  title: "Early Release OPERA Cloud Front Desk Master Data Management API"
  termsOfService: "https://www.oracle.com/legal/terms.html"
  contact:
    email: "hospitality_apis_ww_grp@oracle.com"
  license:
    name: "UPL"
    url: "https://opensource.org/licenses/upl"
basePath: "/fof/config/v0"
tags:
- name: "CashieringConfig"
  description: "Cashiering configurations affect the control and management of financial\
    \ transactions at your property. You can configure cashiering components for articles\
    \ for sale, cancellation handling, deposits, folios, settlements, exchange rates,\
    \ payment methods and so on."
schemes:
- "https"
produces:
- "application/json"
paths:
  /hotels/{hotelId}/exchangeRates/{currencyCode}:
    get:
      tags:
      - "CashieringConfig"
      summary: "Operation to fetch FuturePastExchangeRates."
      description: "Operation to Fetch Future Past Exchange Rates. <p><strong>OperationId:</strong>getFuturePastExchangeRates</p>"
      operationId: "getFuturePastExchangeRates"
      parameters:
      - name: "currencyCode"
        in: "path"
        description: "Currency Code in OPERA"
        required: true
        type: "string"
        maxLength: 2000
        minLength: 1
      - name: "hotelId"
        in: "path"
        description: "Unique ID of the hotel in OPERA"
        required: true
        type: "string"
        maxLength: 2000
        minLength: 1
      - name: "exchangeTypes"
        in: "query"
        description: "E-certificate conversion."
        required: true
        type: "string"
        uniqueItems: true
        enum:
        - "Cash"
        - "Settlement"
        - "Posting"
        - "Check"
        - "TACommission"
        - "Membership"
        - "Certificate"
        x-example: "Cash"
      - name: "dateRangeStart"
        in: "query"
        required: false
        type: "string"
        format: "date"
      - name: "dateRangeEnd"
        in: "query"
        required: false
        type: "string"
        format: "date"
      - name: "authorization"
        in: "header"
        description: "Bearer token that needs to be passed which is generated post\
          \ user authentication"
        required: true
        type: "string"
      - name: "x-app-key"
        in: "header"
        description: "Client or Partner’s Application Key"
        required: true
        type: "string"
        pattern: "^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}$"
      - name: "x-hotelid"
        in: "header"
        description: "Mandatory parameter to identify the hotel code where the end\
          \ user is logged in"
        required: true
        type: "string"
      - name: "x-externalsystem"
        in: "header"
        description: "External system code."
        required: false
        type: "string"
        maxLength: 80
        x-example: ""
      - name: "Accept-Language"
        in: "header"
        description: "Language code"
        required: false
        type: "string"
      responses:
        "200":
          description: "Collection of exchange rates and their information."
          examples:
            application/json:
            - exchangeType:
              - "Cash"
              currency:
                code: "AUD"
              baseCurrency:
                code: "USD"
              beginDate: "2020-09-01"
              buyRate: "1"
              buyCommission: "0"
              status: "Future"
            - exchangeType:
              - "Cash"
              currency:
                code: "AUD"
              baseCurrency:
                code: "USD"
              beginDate: "2020-01-01 00:28:45.0"
              buyRate: "1.34"
              buyCommission: "0"
              status: "Current"
            - exchangeType:
              - "Cash"
              currency:
                code: "AUD"
              baseCurrency:
                code: "USD"
              beginDate: "2016-09-01 13:04:40.0"
              buyRate: "5"
              buyCommission: "5"
              status: "Past"
          headers:
            Content-Language:
              type: "string"
              description: "Audience language"
              pattern: "[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*"
              x-example: "en-GB"
          schema:
            $ref: "#/definitions/futurePastExchangeRates"
        "204":
          description: "FuturePastExchangeRates not found."
definitions:
  futurePastExchangeRates:
    type: "array"
    description: "Collection of exchange rates and their information."
    items:
      $ref: "#/definitions/exchangeRateType"
    maxItems: 4000
  exchangeRateType:
    type: "object"
    properties:
      hotelId:
        type: "string"
        description: "Property where exchange rate is set."
        minLength: 0
        maxLength: 20
      exchangeType:
        type: "array"
        description: "Type for exchange calculation."
        items:
          $ref: "#/definitions/currencyExchangeType"
        maxItems: 4000
      currency:
        description: "Currency code."
        $ref: "#/definitions/codeDescriptionType"
      baseCurrency:
        description: "Exchange rate base currency."
        $ref: "#/definitions/codeDescriptionType"
      beginDate:
        type: "string"
        format: "date-time"
        description: "Date on which the rate is to become active."
      buyRate:
        type: "number"
        description: "Buy Rate for foreign currency."
      buyCommission:
        type: "number"
        description: "Percentage of the amount that is to be a commission for the\
          \ currency buy operation."
      sellRate:
        type: "number"
        description: "Sell Rate for foreign currency."
      sellCommission:
        type: "number"
        description: "Percentage of the amount that is to be a commission for the\
          \ currency sell operation."
      comment:
        type: "string"
        description: "Comments associated with the exchange rate."
        maxLength: 2000
      status:
        description: "Status past, present, or future."
        $ref: "#/definitions/statusTypes"
    description: "Exchange rate configuration type."
  currencyExchangeType:
    type: "string"
    description: "E-certificate conversion."
    enum:
    - "Cash"
    - "Settlement"
    - "Posting"
    - "Check"
    - "TACommission"
    - "Membership"
    - "Certificate"
  codeDescriptionType:
    type: "object"
    properties:
      code:
        type: "string"
        description: "Code."
        minLength: 0
        maxLength: 20
      description:
        type: "string"
        description: "description."
        minLength: 0
        maxLength: 2000
    description: "This contains a generic code and description information."
  statusTypes:
    type: "string"
    description: "Defines status in terms of time."
    enum:
    - "Future"
    - "Current"
    - "Past"
  exceptionDetailType:
    type: "object"
    required:
    - "title"
    - "type"
    properties:
      type:
        type: "string"
        description: "Absolute URI [RFC3986] that identifies the problem type.  When\
          \ dereferenced, it SHOULD provide a human-readable summary of the problem\
          \ (for example, using HTML)."
      title:
        type: "string"
        description: "Short, human-readable summary of the problem.  The summary SHOULD\
          \ NOT change for subsequent occurrences of the problem, except for purposes\
          \ of localization."
      status:
        type: "integer"
        description: "HTTP status code for this occurrence of the problem, set by\
          \ the origin server."
      detail:
        type: "string"
        description: "Human-readable description specific to this occurrence of the\
          \ problem."
      instance:
        type: "string"
        description: "Absolute URI that identifies the specific occurrence of the\
          \ problem.  It may or may not provide additional information if dereferenced."
      o:errorCode:
        type: "string"
        description: "Application error code, which is different from HTTP error code."
      o:errorPath:
        type: "string"
        description: "Path to the problem at the resource or property level."
      o:errorDetails:
        type: "array"
        description: "Details of the error message, consisting of a hierarchical tree\
          \ structure."
        items:
          $ref: "#/definitions/errorInstance"
      links:
        $ref: "#/definitions/links"
    title: "Error Detail"
    description: "Complex type that contains error details for a REST call."
  errorInstance:
    type: "object"
    required:
    - "title"
    - "type"
    properties:
      type:
        type: "string"
        description: "Absolute URI [RFC3986] that identifies the problem type.  When\
          \ dereferenced, it SHOULD provide a human-readable summary of the problem\
          \ (for example, using HTML)."
      title:
        type: "string"
        description: "Short, human-readable summary of the problem.  The summary SHOULD\
          \ NOT change for subsequent occurrences of the problem, except for purposes\
          \ of localization."
      status:
        type: "integer"
        description: "HTTP status code for this occurrence of the problem, set by\
          \ the origin server."
      detail:
        type: "string"
        description: "Human-readable description specific to this occurrence of the\
          \ problem."
      instance:
        type: "string"
        description: "Absolute URI that identifies the specific occurrence of the\
          \ problem.  It may or may not provide additional information if dereferenced."
      o:errorCode:
        type: "string"
        description: "Application error code, which is different from HTTP error code."
      o:errorPath:
        type: "string"
        description: "Path to the problem at the resource or property level."
    title: "Error Instance Details"
    description: "Complex type that contains error instance details for a REST call."
  links:
    type: "array"
    items:
      $ref: "#/definitions/instanceLink"
  instanceLink:
    type: "object"
    required:
    - "href"
    - "method"
    - "operationId"
    - "rel"
    properties:
      href:
        type: "string"
        description: "URI [RFC3986] or URI Template [RFC6570]. If the value is set\
          \ to URI Template, then the \"templated\" property must be set to true."
      rel:
        type: "string"
        description: "Name of the link relation that, in addition to the type property,\
          \ can be used to retrieve link details. For example, href or profile."
      templated:
        type: "boolean"
        description: "Boolean flag that specifies that \"href\" property is a URI\
          \ or URI Template. If the property is a URI template, set this value to\
          \ true. By default, this value is false."
        default: false
      method:
        type: "string"
        description: "HTTP method for requesting the target of the link."
        enum:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "PATCH"
        - "OPTIONS"
        - "HEAD"
      targetSchema:
        type: "string"
        description: "Link to the metadata of the resource, such as JSON-schema, that\
          \ describes the resource expected when dereferencing the target resource.."
      operationId:
        type: "string"
        description: "The operationId of the path you can call to follow this link.\
          \  This allows you to look up not only the path and method, but the description\
          \ of that path and any parameters you need to supply."
      title:
        type: "string"
        description: "Exact copy of the \"summary\" field on the linked operation."
    description: "Metadata describing link description objects that MAY appear in\
      \ the JSON instance representation."
parameters:
  authKey:
    name: "authorization"
    in: "header"
    description: "Bearer token that needs to be passed which is generated post user\
      \ authentication"
    required: true
    type: "string"
  x-app-key:
    name: "x-app-key"
    in: "header"
    description: "Client or Partner’s Application Key"
    required: true
    type: "string"
    pattern: "^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}$"
  x-hotelid:
    name: "x-hotelid"
    in: "header"
    description: "Mandatory parameter to identify the hotel code where the end user\
      \ is logged in"
    required: true
    type: "string"
  x-externalsystem:
    name: "x-externalsystem"
    in: "header"
    description: "External system code."
    required: false
    type: "string"
    maxLength: 80
    x-example: ""
  Accept-Language:
    name: "Accept-Language"
    in: "header"
    description: "Language code"
    required: false
    type: "string"
responses:
  "400":
    description: "Bad Request"
    schema:
      $ref: "#/definitions/exceptionDetailType"
  "401":
    description: "Unauthorized"
  "403":
    description: "Forbidden"
  "404":
    description: "Resource not found"
    schema:
      $ref: "#/definitions/exceptionDetailType"
  "405":
    description: "Method not allowed"
  "406":
    description: "Not acceptable."
  "413":
    description: "Request Entity Too Large"
  "414":
    description: "Request URI Too Large"
  "415":
    description: "Unsupported Media Type"
  "500":
    description: "System Error"
    schema:
      $ref: "#/definitions/exceptionDetailType"
  "502":
    description: "Bad Gateway"
  "503":
    description: "Service Unavailable"
externalDocs:
  description: "Find out more about Oracle Hospitality"
  url: "https://docs.oracle.com/en/industries/hospitality/integration_platforms.html"
